import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { ListItem } from '@/components/ListItem';
import {
	SiSolidity,
	SiGit,
	SiMongodb,
	SiNextdotjs as SiNextDotJs,
	SiNodedotjs as SiNodeDotJs,
	SiPostgresql,
	SiReact,
	SiStyledcomponents as SiStyledComponents,
	SiTailwindcss,
	SiTypescript,
	SiYarn,
  SiPowershell,
} from 'react-icons/si';
import { SlLocationPin } from 'react-icons/sl';
import { Cursor, useTypewriter } from 'react-simple-typewriter';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [text, count] = useTypewriter({
    words: [
      "Hey, I'm Piset 👋",
    ],
    loop: true,
    delaySpeed: 2000
  })

  return (
    <>
      <Head>
        <title>Piset Heang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className='bg-neutral-700 inline-block py-1 px-2 mb-1 rounded-full'>
          <div className='flex items-center space-x-1'>
            <span>{SlLocationPin({className: 'h-4 w-4'})}</span>
            <span className='text-sm'>Phnom Penh, Cambodia</span>
          </div>
        </div>
        <p className='text-4xl font-black sm:text-5xl'>
          {text}
          <Cursor cursorColor='#F7AB0A' />
        </p>
        <div className='p-2'/>
        <p className='font-extralight text-lg text-neutral-400'>I am a Full-stack developer with a focus on web development and blockchain. Passionate about creating innovative solutions and leveraging the latest technologies.</p>
        <div className='p-4' />

        <p className='text-2xl sm:text-3xl font-extrabold mb-8'>What do I do?</p>
        <div className='p-4' />

        <p className='text-2xl sm:text-3xl font-extrabold mb-1'>Technologies</p>
        <p className='text-neutral-400 text-lg font-extralight mb-8'>I’ve worked with a range technologies in the web development world.<br />From Frontend to Backend.</p>
        <ul className="grid grid-cols-2 gap-4 sm:grid-cols-4">
					<ListItem icon={SiGit} text="Git" />
					<ListItem icon={SiNodeDotJs} text="Node.js" />
					<ListItem icon={SiTypescript} text="TypeScript" />
					<ListItem icon={SiReact} text="React.js" />
					<ListItem icon={SiNextDotJs} text="Next.js" />
					<ListItem icon={SiSolidity} text="Solidity" />
					<ListItem icon={SiPowershell} text="Shell" />
					<ListItem icon={SiYarn} text="Yarn" />
					<ListItem icon={SiTailwindcss} text="TailwindCSS" />
					<ListItem icon={SiStyledComponents} text="styled-components" />
					<ListItem icon={SiPostgresql} text="Postgres" />
					<ListItem icon={SiMongodb} text="Mongo" />
				</ul>
        <div className={styles.center} />
      </div>
    </>
  )
}
